### ISSUE TITLE
Actividad. 4 Mapa mental 1BS

### ISSUE THREAD

**Issue by AdriHernandez-Martinez0863** [SistemasTecTlaxiaco/actividad-4-mapa-mental-AdriHernandez-Martinez0863#1]
[Mapa mental-Comunicacion Oral y Escrita.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-mapa-mental-AdriHernandez-Martinez0863/files/9641031/Mapa.mental-Comunicacion.Oral.y.Escrita.pdf)

**Comment by Jaczibeth** [comment]
Obtuviste 17% del 20%
Presentas mala organización en tu estructura, faltas de ortografía,

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
